### ISSUE TITLE
Error in timeToDescription for dates over 24hrs old

### ISSUE THREAD

**Issue by freb** [pusher-community/pusher-realtime-chat-widget#1]
PusherChatWidget.timeToDescription on line 249 has a bug on line 251:

time = Date.parse(time);

This should actually be:

time = new Date(Date.parse(time));

Or it will fail if execution reaches line 271:

desc = time.getDay()...

because Date.parse(time) returns a number which has no .getDay() method. My code returns a Date instance.

**Comment by leggetter** [comment]
Thanks @freb. Will sort out the #2 when I get a chance.
