### ISSUE TITLE
Timestamp: "NaN undefined"

### ISSUE THREAD

**Issue by LucasCioffi** [pusher-community/pusher-realtime-chat-widget#10]
Hi, I'm wondering what might cause the timestamp on my chats to display as "NaN undefined".  Otherwise the chat example is working great.

I'm deploying this on Ruby 1.9.3p194, Rails 3.2.5, and Unicorn.

This issue only seems to be happening locally and not on production (Heroku), so this is not a major issue.

**Comment by robhawkes** [comment]
Hi @LucasCioffi, are you still seeing this problem when you run locally?

**Comment by LucasCioffi** [comment]
Hi Robin, I am still seeing this locally, but if no one else can reproduce, we might as well close the issue.

**Comment by robhawkes** [comment]
Ok, well I'll close it unless someone can work out what might be causing it.
