### ISSUE TITLE
Text Change to README

### ISSUE THREAD

**Issue by LucasCioffi** [pusher-community/pusher-realtime-chat-widget#18]
This is in the Ruby part of the README:

```
var pusher = new Pusher('49e26cb8e9dde3dfc009')
```

Perhaps it should probably change to the following to match the instructions at http://pusher.com/tutorials/realtime_chat_widget

```
var pusher = new Pusher('YOUR_APP_KEY')
```

Or some other way to let beginners know that they should replace the key with their own.

**Comment by zimbatm** [comment]
Thanks for the tip Lucas
