### ISSUE TITLE
PusherChatWidget.prototype._chatMessageReceived isn't firing

### ISSUE THREAD

**Issue by LucasCioffi** [pusher-community/pusher-realtime-chat-widget#20]
PusherChatWidget.prototype._chatMessageReceived isn't firing even though it is attached to PusherChatWidget in the DOM.

```
PusherChatWidget.prototype._chatMessageReceived = function(data) {
  console.log("message received");
  (the rest of the code goes here...)
}
```

Everything else seems to work.  I can save the message to my database and receive a response from Pusher.  

What does chatMessageReceived depend on in the main Pusher JS that I can verify is correct in my Rails 4 setup?

Any other suggestions for what I should look into to get it working?  Thanks!

**Comment by zimbatm** [comment]
Hi,

try turning the logs on the Pusher object. I think it's `Pusher.log = console.log.bind(console)`. It should tell you if you've subscribed and received the message.

**Comment by leggetter** [comment]
You can see where that function is called here:
https://github.com/pusher/pusher-realtime-chat-widget/blob/master/src/js/PusherChatWidget.js#L38

I think debug is on by default https://github.com/pusher/pusher-realtime-chat-widget/blob/master/src/js/PusherChatWidget.js#L21

But you can also set this by passing in a `debug` option:

``` js
var pusher = new Pusher("APP_KEY")
var chatWidget = new PusherChatWidget(pusher, {
  appendTo: "#pusher_chat_widget",
  chatEndPoint: "/chat",
  debug: true
});
```

Then see https://pusher.com/docs/debugging#pusher_logging for an idea of the sort of information you should see in the JavaScript debug console.

This page actually uses the chat widget so if there were any bugs we'd also see them there:
https://pusher.com/tutorials/realtime_chat_widget

**Comment by LucasCioffi** [comment]
**What could be the reason why I can successfully send but not receive?  Thanks so much for your help on this!**

Thank you for the tips.  I posted the console log messages below.  Compared to https://pusher.com/tutorials/realtime_chat_widget I see the symptom of a problem in that I do not receive this log message:

```
Pusher : Event recd : {"event":"chat_message","data":{"id"...
```

To confirm, I also can't get the following log message to display in the console.

```
PusherChatWidget.prototype._chatMessageReceived = function(data) {
  console.log("message received");
  // more code goes here...
}
```

This indicates to me that I'm not receiving any chat messages.

DEVELOPMENT:

```
Pusher : State changed : connecting -> connected live
Pusher : Event sent : {"event":"pusher:subscribe","data":{"channel":"RTANG"}}
Pusher : Event recd : {"event":"pusher_internal:subscription_succeeded","data":{},"channel":"RTANG"}
Pusher : No callbacks for pusher:subscription_succeeded
POST http://localhost:3000/live_chat #This is when I posted the chat message.
200 OK 1.71s    
Chat message sent. Result: success : {"body":"{\"activity\":{\"id\":\"72595490-c1dc-0132-d3d4-002500a34e9c\",\"body\":\"test12\",\"published\":\"2015-04-10 14:22:19 -0400\",\"type\":\"chat-message\",\"actor\":{\"displayName\":null,\"objectType\":\"person\",\"image\":{\"url\":\"http://www.gravatar.com/avatar/00000000000000000000000000000000?d=wavatar\\u0026s=48\",\"width\":48,\"height\":48}}},\"pusherResponse\":{}}"}
```

PRODUCTION at https://pusher.com/tutorials/realtime_chat_widget

```
Pusher : State changed : connecting -> connected
Pusher : Event sent : {"event":"pusher:subscribe","data":{"channel":"https-pusher-com-tutorials-realtime_chat_widget"}}
Pusher : Event recd : {"event":"pusher_internal:subscription_succeeded","data":{},"channel":"https-pusher-com-tutorials-realtime_chat_widget"}
Pusher : No callbacks on https-pusher-com-tutorials-realtime_chat_widget for pusher:subscription_succeeded
POST https://pusher.com/tutorials_ajax/chat_handler
200 OK 87ms 
Pusher : Event recd : {"event":"chat_message","data":{"id":"829e86e0-c1de-0132-d540-320e898634c8","body":"b","published":"2015-04-10T18:37:05+00:00","type":"chat-message","actor":{"displayName":"a","objectType":"person","image":{"url":"http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=80&d=mm&r=g","width":48,"height":48}}},"channel":"https-pusher-com-tutorials-realtime_chat_widget"}
Chat message sent. Result: success : {"activity":{"id":"829e86e0-c1de-0132-d540-320e898634c8","body":"b","published":"2015-04-10T18:37:05+00:00","type":"chat-message","actor":{"displayName":"a","objectType":"person","image":{"url":"http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=80&d=mm&r=g","width":48,"height":48}}},"pusherResponse":true,"channelName":"https-pusher-com-tutorials-realtime_chat_widget"}
```

**Comment by LucasCioffi** [comment]
Aha!  The reason for my error was that I was using two different channel names in my JS and server code.  So it seemed to be sending on one channel and receiving on another, so that's why I didn't see anything coming back.

Thanks for the help and a great tool!

**Comment by leggetter** [comment]
@LucasCioffi great to hear you've identified what was going wrong.
