### ISSUE TITLE
Sample code has typo/missing ' at end of width

### ISSUE THREAD

**Issue by blanier** [pusher-community/pusher-realtime-chat-widget#23]
On https://pusher.com/tutorials/realtime_chat_widget
section entitled "Personalise by integrating with your existing user accounts"

$options = array(
  'displayName' => 'Dave the PHP Guru',
  'image' => array(
  'url' => 'path_to_avatar_for_dave.png',
  'height => '48',
  'width => '48'
  )
);

**Comment by zimbatm** [comment]
Thanks, fixed :)
