### ISSUE TITLE
unable to receive message

### ISSUE THREAD

**Issue by arafay696** [pusher-community/pusher-realtime-chat-widget#32]
i am using PHP library and i have complete all the steps, and also double check my APP KEY,ID and Secret: but when i try this:

http://localhost/pusher-realtime-chat/src/

Error:
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4001,"message":"Could not find app by key API_KEY. Perhaps you're connecting to the wrong cluster."}}}

**Comment by luismfonseca** [comment]
Your apps were created in `ap2`, so you need to specify the cluster in the Pusher instance.

So you need to update [this](https://github.com/pusher-community/pusher-realtime-chat-widget/blob/044148e66b5cbb88be27452d7f6cdd5ed5365f3c/src/php/chat.php#L27) for example, to pass a `options` field with `cluster => 'ap2'`. And also in the javascript [client](https://github.com/pusher-community/pusher-realtime-chat-widget/blob/044148e66b5cbb88be27452d7f6cdd5ed5365f3c/src/nodejs/app.js#L16) as well.

Perhaps I should create a MR to improve this...
