### ISSUE TITLE
Widget display adjustment

### ISSUE THREAD

**Issue by charleslcso** [pusher-community/pusher-realtime-chat-widget#5]
I want to keep the number of messages displayed remain fixed at 3. When there are more than 3 messages, it will autoscroll. 

How do I control that?

**Comment by leggetter** [comment]
You can control the height of the messages area by setting a fixed height value for the `ul` element which contains the message `li` elements.

https://github.com/pusher/pusher-realtime-chat-widget/blob/master/src/pusher-chat-widget.css#L95

e.g.

```
height: 183px;
```
